"""Shared helpers for the spec generators (gen_strings, gen_tokens, gen_analytics).

Every generator writes through `Output.write`, which supports a `--check` mode: nothing is
written, and the process exits non-zero if any generated file on disk differs from what the
generator would produce. CI runs the generators with --check so generated code never drifts.
"""
import importlib.util
import os
import sys

SPEC = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(SPEC)

# Generated file destinations (ROADMAP Phase 0). Android lives under the :core:designsystem module,
# iOS under the Core/DesignSystem target; analytics goes to the :core:analytics / Analytics targets.
ANDROID_DESIGNSYSTEM = os.path.join(REPO, "android", "core", "designsystem")
ANDROID_ANALYTICS = os.path.join(REPO, "android", "core", "analytics")
IOS_CORE = os.path.join(REPO, "ios", "Packages", "Core", "Sources")

KOTLIN_PKG_DESIGNSYSTEM = "app.scanfit.core.designsystem"
KOTLIN_PKG_ANALYTICS = "app.scanfit.core.analytics"


PIP_NAMES = {"PIL": "pillow"}


def replace_json_array(text: str, key: str, items: list) -> str:
    """Replaces the array of top-level `key` in a JSON document's text, leaving every other byte as it is.

    Works whatever the file's formatting (one case per line, Prettier, tabs or spaces): the array is found by bracket
    matching (strings skipped) and rewritten one item per line in the file's own indentation.
    """
    import json
    start = text.index(f'"{key}"')
    open_at = text.index("[", start)
    depth, i, in_string = 0, open_at, False
    while True:
        ch = text[i]
        if in_string:
            if ch == "\\":
                i += 1
            elif ch == '"':
                in_string = False
        elif ch == '"':
            in_string = True
        elif ch in "[{":
            depth += 1
        elif ch in "]}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    line_start = text.rindex("\n", 0, start) + 1
    outer = text[line_start:start]  # the key's own indentation
    unit = "\t" if outer.startswith("\t") else "  "
    inner = outer + unit
    body = ",\n".join(inner + json.dumps(item, ensure_ascii=False, separators=(", ", ": ")) for item in items)
    return text[:open_at] + "[\n" + body + "\n" + outer + "]" + text[i + 1:]


def require(*modules: str):
    """Exit with the setup steps (not a traceback) when a third-party package the tool needs is missing."""
    missing = [m for m in modules if importlib.util.find_spec(m) is None]
    if not missing:
        return
    names = ", ".join(PIP_NAMES.get(m, m) for m in missing)
    print(f"error: missing Python package(s): {names}\n"
          "Set up once from the repo root (macOS Python is 'externally managed', so use a virtual environment; "
          ".venv/ is git-ignored):\n"
          "    python3 -m venv .venv && source .venv/bin/activate\n"
          "    pip install -r spec/tools/requirements.txt\n"
          "Then re-run this command in the same shell.", file=sys.stderr)
    sys.exit(2)


def banner(generator: str, comment: str = "//") -> str:
    return (f"{comment} GENERATED by spec/tools/{generator} - DO NOT EDIT.\n"
            f"{comment} Change the spec source and re-run the generator (CI checks for drift).\n")


class Output:
    """Collects generated files, then writes them or checks them against disk."""

    def __init__(self, check: bool):
        self.check = check
        self.drift = []
        self.written = []

    def write(self, path: str, content: str):
        if not content.endswith("\n"):
            content += "\n"
        current = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                current = f.read()
        if current == content:
            return
        if self.check:
            self.drift.append(os.path.relpath(path, REPO))
            return
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        self.written.append(os.path.relpath(path, REPO))

    def finish(self, label: str):
        if self.check:
            if self.drift:
                print(f"✗ {label}: generated files are out of date:", file=sys.stderr)
                for p in self.drift:
                    print(f"    {p}", file=sys.stderr)
                print(f"  Re-run spec/tools/{label} and commit the result.", file=sys.stderr)
                sys.exit(1)
            print(f"✓ {label}: generated files up to date")
        else:
            for p in self.written:
                print(f"  wrote {p}")
            print(f"✓ {label}: {len(self.written)} file(s) written")


def die(errors, label):
    for e in errors:
        print(f"  ✗ {e}", file=sys.stderr)
    print(f"{label} failed ({len(errors)} error(s))", file=sys.stderr)
    sys.exit(1)


def camel(snake: str, upper_first: bool = False) -> str:
    parts = snake.split("_")
    out = parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])
    return out[:1].upper() + out[1:] if upper_first else out
