"""Shared helpers for the spec generators (gen_strings, gen_tokens, gen_analytics).

Every generator writes through `Output.write`, which supports a `--check` mode: nothing is
written, and the process exits non-zero if any generated file on disk differs from what the
generator would produce. CI runs the generators with --check so generated code never drifts.
"""
import os
import sys

SPEC = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(SPEC)

# Generated file destinations (ROADMAP Phase 0). Android lives under the :core:designsystem module,
# iOS under the Core/DesignSystem target; analytics goes to the :core:analytics / Analytics targets.
ANDROID_DESIGNSYSTEM = os.path.join(REPO, "android", "core", "designsystem")
ANDROID_ANALYTICS = os.path.join(REPO, "android", "core", "analytics")
IOS_CORE = os.path.join(REPO, "ios", "Packages", "Core", "Sources")

KOTLIN_PKG_DESIGNSYSTEM = "app.scanfit.core.designsystem"
KOTLIN_PKG_ANALYTICS = "app.scanfit.core.analytics"


def banner(generator: str, comment: str = "//") -> str:
    return (f"{comment} GENERATED by spec/tools/{generator} - DO NOT EDIT.\n"
            f"{comment} Change the spec source and re-run the generator (CI checks for drift).\n")


class Output:
    """Collects generated files, then writes them or checks them against disk."""

    def __init__(self, check: bool):
        self.check = check
        self.drift = []
        self.written = []

    def write(self, path: str, content: str):
        if not content.endswith("\n"):
            content += "\n"
        current = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                current = f.read()
        if current == content:
            return
        if self.check:
            self.drift.append(os.path.relpath(path, REPO))
            return
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        self.written.append(os.path.relpath(path, REPO))

    def finish(self, label: str):
        if self.check:
            if self.drift:
                print(f"✗ {label}: generated files are out of date:", file=sys.stderr)
                for p in self.drift:
                    print(f"    {p}", file=sys.stderr)
                print(f"  Re-run spec/tools/{label} and commit the result.", file=sys.stderr)
                sys.exit(1)
            print(f"✓ {label}: generated files up to date")
        else:
            for p in self.written:
                print(f"  wrote {p}")
            print(f"✓ {label}: {len(self.written)} file(s) written")


def die(errors, label):
    for e in errors:
        print(f"  ✗ {e}", file=sys.stderr)
    print(f"{label} failed ({len(errors)} error(s))", file=sys.stderr)
    sys.exit(1)


def camel(snake: str, upper_first: bool = False) -> str:
    parts = snake.split("_")
    out = parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])
    return out[:1].upper() + out[1:] if upper_first else out
