// GENERATED by spec/tools/gen_tokens.py - DO NOT EDIT.
// Change the spec source and re-run the generator (CI checks for drift).

package app.scanfit.core.designsystem.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Shapes
import androidx.compose.material3.Typography
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.animation.core.CubicBezierEasing
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Semantic colours, same role names on both platforms. Status roles (success, warning) extend Material. */
@Immutable
data class ScanFitColors(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
    val success: Color,
    val onSuccess: Color,
    val successContainer: Color,
    val onSuccessContainer: Color,
    val warning: Color,
    val onWarning: Color,
    val warningContainer: Color,
    val onWarningContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val scrim: Color,
    val isDark: Boolean,
)

val ScanFitLightColors = ScanFitColors(
    primary = Color(0xFF3F4DB8),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE1E4FF),
    onPrimaryContainer = Color(0xFF10186B),
    background = Color(0xFFFAFAFC),
    onBackground = Color(0xFF1A1A21),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF1A1A21),
    surfaceVariant = Color(0xFFEDEDF3),
    onSurfaceVariant = Color(0xFF4A4A58),
    outline = Color(0xFF767689),
    outlineVariant = Color(0xFFCFCFD9),
    success = Color(0xFF1B7A3A),
    onSuccess = Color(0xFFFFFFFF),
    successContainer = Color(0xFFDDF2E2),
    onSuccessContainer = Color(0xFF0B3A1A),
    warning = Color(0xFF9A5A00),
    onWarning = Color(0xFFFFFFFF),
    warningContainer = Color(0xFFFFEFD0),
    onWarningContainer = Color(0xFF4A2A00),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    scrim = Color(0xFF000000),
    isDark = false,
)

val ScanFitDarkColors = ScanFitColors(
    primary = Color(0xFFB8C1FF),
    onPrimary = Color(0xFF141C73),
    primaryContainer = Color(0xFF2D3894),
    onPrimaryContainer = Color(0xFFDFE2FF),
    background = Color(0xFF121217),
    onBackground = Color(0xFFE4E4EC),
    surface = Color(0xFF1A1A21),
    onSurface = Color(0xFFE4E4EC),
    surfaceVariant = Color(0xFF2A2A34),
    onSurfaceVariant = Color(0xFFC5C5D3),
    outline = Color(0xFF8E8EA2),
    outlineVariant = Color(0xFF454553),
    success = Color(0xFF7ED79A),
    onSuccess = Color(0xFF00391A),
    successContainer = Color(0xFF0F4F27),
    onSuccessContainer = Color(0xFFB9F0CA),
    warning = Color(0xFFFFB95C),
    onWarning = Color(0xFF4A2900),
    warningContainer = Color(0xFF6A3D00),
    onWarningContainer = Color(0xFFFFDDB3),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    scrim = Color(0xFF000000),
    isDark = true,
)

/** Raw neutral ramp, for illustration and decorative use. Prefer the semantic roles. */
object ScanFitNeutral {
    val n50 = Color(0xFFFAFAFC)
    val n100 = Color(0xFFF1F1F5)
    val n200 = Color(0xFFE3E3EA)
    val n300 = Color(0xFFCFCFD9)
    val n400 = Color(0xFFA4A4B4)
    val n500 = Color(0xFF767689)
    val n600 = Color(0xFF5A5A6B)
    val n700 = Color(0xFF454553)
    val n800 = Color(0xFF2E2E39)
    val n900 = Color(0xFF1A1A21)
    val n950 = Color(0xFF0E0E12)
}

object ScanFitSpacing {
    val xs = 4.dp
    val sm = 8.dp
    val md = 12.dp
    val lg = 16.dp
    val xl = 24.dp
    val xxl = 32.dp
    val screenMargin = 16.dp
    val minTouchTarget = 48.dp
}

object ScanFitRadius {
    val card = 16.dp
    val button = 12.dp
    val chip = 999.dp
}

object ScanFitMotion {
    const val MICRO_MS = 150
    const val STANDARD_MS = 250
    const val EMPHASISED_MS = 350
    val standardEasing = CubicBezierEasing(0.2f, 0.0f, 0.0f, 1.0f)
    val emphasisedDecelerateEasing = CubicBezierEasing(0.05f, 0.7f, 0.1f, 1.0f)
}

/**
 * Type scale. FontFamily.Default is Roboto on Android; Roboto Flex + Noto Sans Devanagari
 * (UI_UX §4) is not bundled yet (APK size budget, ARCHITECTURE §11).
 */
object ScanFitType {
    val display = TextStyle(fontFamily = FontFamily.Default, fontSize = 32.sp, fontWeight = FontWeight.Bold, lineHeight = 40.sp)
    val title = TextStyle(fontFamily = FontFamily.Default, fontSize = 22.sp, fontWeight = FontWeight.SemiBold, lineHeight = 28.sp)
    val headline = TextStyle(fontFamily = FontFamily.Default, fontSize = 18.sp, fontWeight = FontWeight.SemiBold, lineHeight = 24.sp)
    val body = TextStyle(fontFamily = FontFamily.Default, fontSize = 16.sp, fontWeight = FontWeight.Normal, lineHeight = 24.sp)
    val label = TextStyle(fontFamily = FontFamily.Default, fontSize = 14.sp, fontWeight = FontWeight.Medium, lineHeight = 20.sp)
    val caption = TextStyle(fontFamily = FontFamily.Default, fontSize = 12.sp, fontWeight = FontWeight.Normal, lineHeight = 16.sp)
    val figure = TextStyle(fontFamily = FontFamily.Default, fontSize = 16.sp, fontWeight = FontWeight.SemiBold, lineHeight = 24.sp, fontFeatureSettings = "tnum")
}

private val ScanFitMaterialTypography = Typography(
    displayMedium = ScanFitType.display,
    titleLarge = ScanFitType.title,
    titleMedium = ScanFitType.headline,
    bodyLarge = ScanFitType.body,
    bodyMedium = ScanFitType.body,
    labelLarge = ScanFitType.label,
    bodySmall = ScanFitType.caption,
    labelSmall = ScanFitType.caption,
)

private val ScanFitShapes = Shapes(
    medium = RoundedCornerShape(ScanFitRadius.button),
    large = RoundedCornerShape(ScanFitRadius.card),
)

private fun ScanFitColors.toLightScheme() = lightColorScheme(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = primaryContainer,
    onPrimaryContainer = onPrimaryContainer,
    background = background,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    surfaceVariant = surfaceVariant,
    onSurfaceVariant = onSurfaceVariant,
    outline = outline,
    outlineVariant = outlineVariant,
    error = error,
    onError = onError,
    errorContainer = errorContainer,
    onErrorContainer = onErrorContainer,
    scrim = scrim,
)

private fun ScanFitColors.toDarkScheme() = darkColorScheme(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = primaryContainer,
    onPrimaryContainer = onPrimaryContainer,
    background = background,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    surfaceVariant = surfaceVariant,
    onSurfaceVariant = onSurfaceVariant,
    outline = outline,
    outlineVariant = outlineVariant,
    error = error,
    onError = onError,
    errorContainer = errorContainer,
    onErrorContainer = onErrorContainer,
    scrim = scrim,
)

val LocalScanFitColors = staticCompositionLocalOf { ScanFitLightColors }

/** Access semantic colours that Material lacks (success, warning): `ScanFitTheme.colors.success`. */
object ScanFitTheme {
    val colors: ScanFitColors
        @Composable @ReadOnlyComposable get() = LocalScanFitColors.current
}

@Composable
fun ScanFitTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit,
) {
    val colors = if (darkTheme) ScanFitDarkColors else ScanFitLightColors
    CompositionLocalProvider(LocalScanFitColors provides colors) {
        MaterialTheme(
            colorScheme = if (darkTheme) colors.toDarkScheme() else colors.toLightScheme(),
            typography = ScanFitMaterialTypography,
            shapes = ScanFitShapes,
            content = content,
        )
    }
}
