// GENERATED by spec/tools/gen_analytics.py - DO NOT EDIT.
// Change the spec source and re-run the generator (CI checks for drift).

package app.scanfit.core.analytics

/** A parameter value Firebase accepts. Deliberately no free-form String type. */
sealed interface ParamValue {
    @JvmInline value class Text internal constructor(val value: String) : ParamValue
    @JvmInline value class Whole internal constructor(val value: Long) : ParamValue
    @JvmInline value class Flag internal constructor(val value: Boolean) : ParamValue
}

/** Closed set of analytics events. [name] and [params] are what gets sent; nothing else may be. */
sealed interface AnalyticsEvent {
    val name: String
    val params: Map<String, ParamValue>

    /** Public preset id (e.g. `ibps_po`). Public data, not personal data. */
    @JvmInline
    value class ExamId(val value: String) {
        init { require(PATTERN.matches(value)) { "ExamId must match [a-z0-9_]{1,40}" } }
        private companion object { val PATTERN = Regex("^[a-z0-9_]{1,40}$") }
    }

    enum class DocType(val wire: String) {
        PHOTO("photo"),
        POSTCARD_PHOTO("postcard_photo"),
        SIGNATURE("signature"),
        TRIPLE_SIGNATURE("triple_signature"),
        LEFT_THUMB("left_thumb"),
        THUMB_IMPRESSION("thumb_impression"),
        FINGERS("fingers"),
        HANDWRITTEN_DECLARATION("handwritten_declaration"),
        PDF_DOCUMENT("pdf_document"),
        OTHER("other");
    }

    enum class FitStrategy(val wire: String) {
        QUALITY_SEARCH("quality_search"),
        DOWNSCALE("downscale"),
        UPSCALE("upscale"),
        PAD("pad"),
        UPSCALE_THEN_PAD("upscale_then_pad");
    }

    enum class FitResult(val wire: String) {
        OK("ok"),
        TOO_DETAILED("too_detailed"),
        CANNOT_REACH("cannot_reach"),
        ERROR("error");
    }

    enum class MsBucket(val wire: String) {
        LT_250("lt_250"),
        LT_500("lt_500"),
        LT_1000("lt_1000"),
        LT_2000("lt_2000"),
        GTE_2000("gte_2000");
    }

    enum class SecondsBucket(val wire: String) {
        LT_5("lt_5"),
        LT_15("lt_15"),
        LT_30("lt_30"),
        LT_60("lt_60"),
        GTE_60("gte_60");
    }

    enum class CountBucket(val wire: String) {
        N0("n0"),
        N1_5("n1_5"),
        N6_10("n6_10"),
        N11_20("n11_20"),
        N21_PLUS("n21_plus");
    }

    enum class PaywallVariant(val wire: String) {
        A("a"),
        B("b"),
        C("c");
    }

    enum class PaywallTrigger(val wire: String) {
        FREE_LIMIT("free_limit"),
        PRO_FEATURE("pro_feature"),
        SETTINGS("settings");
    }

    enum class Product(val wire: String) {
        PRO_YEARLY("pro_yearly"),
        PRO_LIFETIME("pro_lifetime");
    }

    enum class SyncResult(val wire: String) {
        UPDATED("updated"),
        NOT_MODIFIED("not_modified"),
        FAILED("failed");
    }

    enum class SyncFailureReason(val wire: String) {
        NETWORK("network"),
        BAD_SIGNATURE("bad_signature"),
        STALE_VERSION("stale_version"),
        BAD_SCHEMA("bad_schema"),
        PARSE("parse");
    }

    data class ExamOpened(val examId: ExamId) : AnalyticsEvent {
        override val name = "exam_opened"
        override val params: Map<String, ParamValue> = mapOf(
            "exam_id" to ParamValue.Text(examId.value),
        )
    }

    data class FlowStarted(val docType: DocType) : AnalyticsEvent {
        override val name = "flow_started"
        override val params: Map<String, ParamValue> = mapOf(
            "doc_type" to ParamValue.Text(docType.wire),
        )
    }

    data class FitCompleted(val docType: DocType, val strategy: FitStrategy, val msBucket: MsBucket, val result: FitResult) : AnalyticsEvent {
        override val name = "fit_completed"
        override val params: Map<String, ParamValue> = mapOf(
            "doc_type" to ParamValue.Text(docType.wire),
            "strategy" to ParamValue.Text(strategy.wire),
            "ms_bucket" to ParamValue.Text(msBucket.wire),
            "result" to ParamValue.Text(result.wire),
        )
    }

    data class ExportSaved(val docType: DocType, val verified: Boolean) : AnalyticsEvent {
        override val name = "export_saved"
        override val params: Map<String, ParamValue> = mapOf(
            "doc_type" to ParamValue.Text(docType.wire),
            "verified" to ParamValue.Flag(verified),
        )
    }

    data class MatchShown(val nExactBucket: CountBucket, val nFix: Int) : AnalyticsEvent {
        override val name = "match_shown"
        override val params: Map<String, ParamValue> = mapOf(
            "n_exact_bucket" to ParamValue.Text(nExactBucket.wire),
            "n_fix" to ParamValue.Whole(nFix.coerceIn(0, 99).toLong()),
        )
    }

    data object FixTapped : AnalyticsEvent {
        override val name = "fix_tapped"
        override val params: Map<String, ParamValue> = emptyMap()
    }

    data class CheckerRun(val issuesCount: Int) : AnalyticsEvent {
        override val name = "checker_run"
        override val params: Map<String, ParamValue> = mapOf(
            "issues_count" to ParamValue.Whole(issuesCount.coerceIn(0, 13).toLong()),
        )
    }

    data class CoachAllGreen(val secondsBucket: SecondsBucket) : AnalyticsEvent {
        override val name = "coach_all_green"
        override val params: Map<String, ParamValue> = mapOf(
            "seconds_bucket" to ParamValue.Text(secondsBucket.wire),
        )
    }

    data class PaywallShown(val variant: PaywallVariant, val trigger: PaywallTrigger) : AnalyticsEvent {
        override val name = "paywall_shown"
        override val params: Map<String, ParamValue> = mapOf(
            "variant" to ParamValue.Text(variant.wire),
            "trigger" to ParamValue.Text(trigger.wire),
        )
    }

    data class Purchase(val product: Product) : AnalyticsEvent {
        override val name = "purchase"
        override val params: Map<String, ParamValue> = mapOf(
            "product" to ParamValue.Text(product.wire),
        )
    }

    data object RewardedCompleted : AnalyticsEvent {
        override val name = "rewarded_completed"
        override val params: Map<String, ParamValue> = emptyMap()
    }

    data class PresetSync(val result: SyncResult) : AnalyticsEvent {
        override val name = "preset_sync"
        override val params: Map<String, ParamValue> = mapOf(
            "result" to ParamValue.Text(result.wire),
        )
    }

    data class PresetSyncFailed(val reason: SyncFailureReason) : AnalyticsEvent {
        override val name = "preset_sync_failed"
        override val params: Map<String, ParamValue> = mapOf(
            "reason" to ParamValue.Text(reason.wire),
        )
    }

    data class PortalFeedback(val accepted: Boolean) : AnalyticsEvent {
        override val name = "portal_feedback"
        override val params: Map<String, ParamValue> = mapOf(
            "accepted" to ParamValue.Flag(accepted),
        )
    }
}
